#pragma once

// User-defined constants

#define THREAD_COUNT 3

#define BUFFER_SIZE 512

#define SERVER_CLIENT_PORT "5059"
#define SERVER_WORKER_PORT "5060"

#define BUSY_WAIT_TIME 10

#define MAX_CLIENTS 4
#define MAX_WORKERS 2

#define CLIENT_THREAD_POOL_SIZE 4

#define CLIENT_BLOCKING_REQUEST_QUEUE_CAPACITY 4
#define CLIENT_BLOCKING_REQUEST_QUEUE_PUT_TIMEOUT 100
#define CLIENT_BLOCKING_REQUEST_QUEUE_TAKE_TIMEOUT INFINITE
#define CLIENT_BLOCKING_REQUEST_QUEUE_FULL_SLEEP_TIME 1000
